In [1]:
%pip install nptyping beartype --upgrade --force

Defaulting to user installation because normal site-packages is not writeable
  Obtaining dependency information for nptyping from https://files.pythonhosted.org/packages/b1/28/92edc05378175de13a3d4986cee7531853634a22b7e5e21a988fa84fde3f/nptyping-2.5.0-py3-none-any.whl.metadata
  Obtaining dependency information for beartype from https://files.pythonhosted.org/packages/81/4a/97ea8a5afb289a25ae7db3b3ef68f0aad892bc1756be94565154877b173e/beartype-0.17.2-py3-none-any.whl.metadata
Note: you may need to restart the kernel to use updated packages.


ERROR: Exception:
Traceback (most recent call last):
  File "c:\Program Files\Python312\Lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "c:\Program Files\Python312\Lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
           ^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python312\Lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
           ^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python312\Lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 90, in read
    data = self.__fp.read(amt)
           ^^^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python312\Lib\http\client.py", line 479, in read
    s = self.fp.read(amt)
        ^^^^^^^^^^^^^^^^^
  File "c:\Program Files\Python312\Lib\socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^

## Scalar value

In [4]:
import numpy as np

a : np.ndarray = np.array(1000) # object to store

display(a) # prints
display(a.shape) # prints the shape of the object () = 0 -Denormalized
display(a.dtype) # prints the dtype of the object
display(type(a)) 
display(a.ndim) # prints the number of dimensions
display(a.size) # prints the size of the object
display(a.itemsize) # prints the itemsize of the object



array(1000)

()

dtype('int32')

numpy.ndarray

0

1

4

## Vector type

In [5]:
import numpy as np

a : np.ndarray = np.array([1,2,3,4]) # object to store [1,2,3,4] = vector

display(f" object {a}") # prints
display(f"objec shape {a.shape}") # prints the shape of the object () = 0 -Denormalized
display(f" Object type {a.dtype}") # prints the dtype of the object
display(f"Object type with global function {type(a)}") # prints the dtype of the
display(f"Number of dimension {a.ndim}") # prints the number of dimensions
display(f"Total items in Array : {a.size}") # prints the size of the object
display(f"{a.itemsize}") # prints the itemsize of the object



' object [1 2 3 4]'

'objec shape (4,)'

' Object type int32'

"Object type with global function <class 'numpy.ndarray'>"

'Number of dimension 1'

'Total items in Array : 4'

'4'

### Matrix

In [8]:
import numpy as np

data = [[0, 1, 2, 3],
        [4, 5, 6, 7],
        [8, 9, 10, 11]]

a : np.ndarray = np.array(data) # object to store [1,2,3,4] = vector

display(f" object {a}") # prints
display(f"objec shape {a.shape}") # prints the shape of the object () = 0 -Denormalized
display(f" Object type {a.dtype}") # prints the dtype of the object
display(f"Object type with global function {type(a)}") # prints the dtype of the
display(f"Number of dimension {a.ndim}") # prints the number of dimensions
display(f"Total items in Array : {a.size}") # prints the size of the object
display(f"{a.itemsize}") # prints the itemsize of the object



' object [[ 0  1  2  3]\n [ 4  5  6  7]\n [ 8  9 10 11]]'

'objec shape (3, 4)'

' Object type int32'

"Object type with global function <class 'numpy.ndarray'>"

'Number of dimension 2'

'Total items in Array : 12'

'4'

# Numpy with NDArray typing support

In [9]:
from nptyping import NDArray, Shape, UInt64
from typing import Any

data : NDArray[Shape["10"], Any] = np.arange(1,10)

print(data)
print(data + 5) # addition operation

[1 2 3 4 5 6 7 8 9]
[ 6  7  8  9 10 11 12 13 14]


In [8]:
d1 : list[int] = [1,2,3,4,5,6,7,8,9,10]
d1 + 5

TypeError: can only concatenate list (not "int") to list

In [4]:
d1 : list[int] = [1,2,3,4,5,6,7,8,9,10]
[i+5 for i in d1 ]

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [3]:
%%time

data : NDArray[Shape["10"], Any] = np.arange(1,10000000)

data + 5 # addition operation

NameError: name 'np' is not defined

In [2]:
%%time
data : list[int] = list(range(1,10000000))

[i + 5  for i in data]# addition operation

CPU times: total: 1.88 s
Wall time: 2.04 s


[6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,


# numpy advanced operations vs list operations

In [10]:
data : list[int] = list(range(1,21))
print(data)
print(data[5:11])
data[5:11] = 1000 # normal python list
print(data)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[6, 7, 8, 9, 10, 11]


TypeError: can only assign an iterable

In [11]:
ndata : NDArray[Shape["20"], Any] = np.arange(1,21)
print(ndata)
print(ndata[5:11])
ndata[5:11] = 1000
print(ndata)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 6  7  8  9 10 11]
[   1    2    3    4    5 1000 1000 1000 1000 1000 1000   12   13   14
   15   16   17   18   19   20]


# Numpy 1d functions

In [7]:
from nptyping import Bool

state_bank : NDArray[Shape["10"],Any] = np.array([1,7,8,10])
#[1,      7,      8,     10]
#[True,  False, False, True]
#variable[[True,  False, False, True]]
#[1,10]
select : NDArray[Shape["10"],Bool]= np.array([True, False, False, True])

state_bank[select]




NameError: name 'np' is not defined

In [5]:
state_bank : NDArray[Shape["4"],Any] = np.array([1,7,8,10])
state_bank % 2 == 0

NameError: name 'np' is not defined

In [12]:
state_bank : NDArray[Shape["4"],Any] = np.array([1,7,8,10])
state_bank[state_bank % 2 == 0]

array([ 8, 10])

In [11]:
state_bank : NDArray[Shape["10"],Any] = np.array([1,7,8,10])

ubl_bank : NDArray[Shape["100"],Any] = np.random.randint(1,100, 20)

display(state_bank)
display(ubl_bank)

array([ 1,  7,  8, 10])

array([32, 50, 40,  5,  2, 98, 70,  2, 39, 70, 55, 17, 43, 31, 64, 50, 62,
       48, 36, 68])

In [10]:
display(state_bank)
display(ubl_bank)

#        4item       search 20 items
np.in1d(state_bank,ubl_bank) # first variable items length returned

NameError: name 'state_bank' is not defined

In [14]:
display(state_bank)
display(ubl_bank)

#        4item       search 20 items
state_bank[np.in1d(state_bank,ubl_bank)] # first variable items length returned

array([ 1,  7,  8, 10])

array([32, 50, 40,  5,  2, 98, 70,  2, 39, 70, 55, 17, 43, 31, 64, 50, 62,
       48, 36, 68])

array([], dtype=int32)

In [18]:
np.intersect1d(state_bank,ubl_bank)

array([7])

In [13]:
x : NDArray[Shape["5"],Any] = np.array([1,3,4,5,7])
y : NDArray[Shape["5"],Any] = np.array([6,3,2,5,100])

display(x)
display(y)
np.where(x > y, x, y)

array([1, 3, 4, 5, 7])

array([  6,   3,   2,   5, 100])

array([  6,   3,   4,   5, 100])

# Create Numpy arrays

In [15]:
a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2, 3],
                                                      [4, 5, 6]])
print(a)

a : NDArray[Shape["Size, Size"], Any] = np.array([[1, 2],
                                                      [4, 5]])
print(a)

a : NDArray[Shape["Size, Size"], Any] = np.array([["A"],
                                                    ["B"]])
print(a)




[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


In [16]:
a : NDArray[Shape["*, *"], Any] = np.array([[1, 2, 3],
                                                      [4, 5, 6]])
print(a)

a : NDArray[Shape["*, *"], Any] = np.array([[1, 2],
                                                      [4, 5]])
print(a)

a : NDArray[Shape["*, *"], Any] = np.array([["A"],
                                                    ["B"]])
print(a)




[[1 2 3]
 [4 5 6]]
[[1 2]
 [4 5]]
[['A']
 ['B']]


In [17]:
np.who()

Name            Shape            Bytes            Type

_               0                0                int32
__              5                20               int32
___             2                8                int32
data            9                36               int32
a               2 x 1            8                str32
state_bank      4                16               int32
ubl_bank        20               80               int32
_12 (___)       2                8                int32
x               5                20               int32
y               5                20               int32
_13 (__)        5                20               int32
_14 (_)         0                0                int32

Upper bound on total bytes  =       208


# Create any dimension array

In [20]:
a : NDArray[Shape["Size"],Any] = np.arange(1,5)
print(a)
a : NDArray[Shape["Size"],Any] = np.arange(1,10)
print(a)

[1 2 3 4]
[1 2 3 4 5 6 7 8 9]


In [19]:
a : NDArray[Shape["Size, Size"],Any] = np.arange(3*4).reshape(3,4)
print(a)
a : NDArray[Shape["Size, Size"],Any] = np.arange(5*6).reshape(5,6)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [18]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(2*3*3).reshape(2,3,3)
print(a)
print('=======')
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [25]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a[::2,::,::]

array([[[ 0,  1],
        [ 2,  3]],

       [[ 8,  9],
        [10, 11]],

       [[16, 17],
        [18, 19]]])

In [24]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a[a%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
np.asarray([1,2,3])

array([1, 2, 3])

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [29]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [28]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]]])

In [27]:
np.ones_like(a)

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [26]:
a : NDArray[Shape["Size, Size, Size"],Any] = np.arange(5*2*2).reshape(5,2,2)
a[[0,-1],::,::]

array([[[ 0,  1],
        [ 2,  3]],

       [[16, 17],
        [18, 19]]])

In [30]:
ndata : NDArray[Shape["20"], Any] = np.arange(1,21)

print(ndata)
print(ndata.min())
print(ndata.max())
print(ndata.argmax())
print(ndata.argmin)
print(ndata.mean())
print(ndata.std())
print(ndata.sum())
print(ndata.cumsum())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
20
19
<built-in method argmin of numpy.ndarray object at 0x00000177E16B6790>
10.5
5.766281297335398
210
[  1   3   6  10  15  21  28  36  45  55  66  78  91 105 120 136 153 171
 190 210]
